### ISSUE TITLE
Data Sets and AZUREML_NATIVE_SHARE_DIRECTORY and context name

### ISSUE THREAD

**Issue by bpatil16** [CatalystCode/detection-amlworkbench#2]
Hi 
I am trying to integrate FasterRcnn with AzureML Bench, I saw your GitHub project. I am new to the using AzureML Workbench.  I had few questions on
1) where is the image data set stored
2) where is the ouput images written.  What is AZUREML_NATIVE_SHARE_DIRECTORY and where is it located
3) whats context name. 
Do you have a detailed steps documentation or point me to one online. thanks in advance

**Comment by olgaliak** [comment]
Hello!
1) Looks like data was too big to be persisted in the repo fro more that few days.   I've updated readme with links where you can get the data.
2) AZUREML_NATIVE_SHARE_DIRECTORY is the directory that's persisted  on the VM between the runs. More info here in [official docs](https://docs.microsoft.com/en-my/azure///machine-learning/preview/how-to-read-write-files).
3) More info on [compute targets here](https://docs.microsoft.com/en-us/azure/machine-learning/preview/how-to-create-dsvm-hdi)
